# Generated by Django 4.1.7 on 2023-11-04 03:13

import LF.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='found_items_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_img', models.ImageField(blank=True, default='null', upload_to=LF.models.filepath)),
                ('item_type', models.CharField(blank=True, default='null', max_length=30)),
                ('date_found', models.DateField(blank=True, default='2000-01-01')),
                ('item_status', models.CharField(blank=True, default='unclaimed', max_length=30)),
                ('found_by_id', models.CharField(blank=True, default='null', max_length=30)),
                ('found_by_name', models.CharField(blank=True, default='null', max_length=30)),
                ('found_by_email', models.CharField(blank=True, default='null', max_length=50)),
                ('found_by_contact', models.CharField(blank=True, default='null', max_length=12)),
                ('q1', models.TextField(blank=True, default='null')),
                ('a1', models.TextField(blank=True, default='null')),
                ('q2', models.TextField(blank=True, default='null')),
                ('a2', models.TextField(blank=True, default='null')),
                ('q3', models.TextField(blank=True, default='null')),
                ('a3', models.TextField(blank=True, default='null')),
                ('q4', models.TextField(blank=True, default='null')),
                ('a4', models.TextField(blank=True, default='null')),
                ('q5', models.TextField(blank=True, default='null')),
                ('a5', models.TextField(blank=True, default='null')),
                ('q6', models.TextField(blank=True, default='null')),
                ('a6', models.TextField(blank=True, default='null')),
                ('q7', models.TextField(blank=True, default='null')),
                ('a7', models.TextField(blank=True, default='null')),
                ('q8', models.TextField(blank=True, default='null')),
                ('a8', models.TextField(blank=True, default='null')),
                ('q9', models.TextField(blank=True, default='null')),
                ('a9', models.TextField(blank=True, default='null')),
                ('q10', models.TextField(blank=True, default='null')),
                ('a10', models.TextField(blank=True, default='null')),
                ('description', models.TextField(blank=True, default='null')),
            ],
        ),
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=50, unique=True)),
                ('user_name', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=10)),
                ('user_type', models.CharField(default='u', max_length=50)),
            ],
        ),
    ]
